import = ["/Users/jwyce/.config/alacritty/tokyonight.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "DankMono Nerd Font Mono"

[window]
decorations = "none"
opacity = 0.9
option_as_alt = "Both"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
