tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "helix-editor/helix"

brew "ripgrep"
brew "atuin"
brew "sd"
brew "bat"
brew "tealdeer"
brew "fd"
brew "fzf"
brew "exa"
brew "fnm"
brew "git"
brew "htop"
brew "starship"
brew "thefuck"
brew "pnpm"
brew "yarn"
brew "tmux"
brew "neovim"
brew "helix"

cask "iterm2"
cask "warp"
cask "hyper"
cask "fig"
cask "brave-browser"
cask "google-chrome"
cask "rectangle"
cask "stats"
cask "alfred"
cask "visual-studio-code"
cask "tableplus"
cask "datagrip"
cask "docker"
cask "notion"
cask "pictogram"
cask "keycastr"
cask "rustdesk"
cask "iina"
# cask "microsoft-teams"
# cask "spacedrive"
