#!/bin/bash

code --install-extension BeardedBear.beardedicons
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.markdown-mermaid
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.path-intellisense
code --install-extension csstools.postcss
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension Gruntfuggly.todo-tree
code --install-extension hediet.vscode-drawio
code --install-extension heybourn.headwind
code --install-extension HowIVSCode.howivscode
code --install-extension IBM.output-colorizer
code --install-extension icrawl.discord-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kleber-swf.unity-code-snippets
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mattpocock.ts-error-translator
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension mike-co.import-sorter
code --install-extension mikestead.dotenv
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension Orta.vscode-jest
code --install-extension pomdtr.excalidraw-editor
code --install-extension Prisma.prisma
code --install-extension redhat.vscode-yaml
code --install-extension rome.rome
code --install-extension rust-lang.rust-analyzer
code --install-extension saratravi.elixir-formatter
code --install-extension SimonSiefke.svg-preview
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sukumo28.wav-preview
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension Tobiah.unity-tools
code --install-extension tomoki1207.pdf
code --install-extension tsandall.opa
code --install-extension Unity.unity-debug
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension withfig.fig
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZixuanChen.vitest-explorer

