local builtin = require("telescope.builtin")
local media = require("telescope")

vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>ps", builtin.live_grep, {})
vim.keymap.set("n", "<leader>pi", media.extensions.media_files.media_files, {})

vim.keymap.set("n", "<leader>gw", require("telescope").extensions.git_worktree.git_worktrees, {})
vim.keymap.set("n", "<leader>gm", require("telescope").extensions.git_worktree.create_git_worktree, {})
vim.keymap.set("n", "<leader>vh", builtin.help_tags, {})
vim.keymap.set("n", "<leader>vb", builtin.buffers, {})
vim.keymap.set("n", "<leader>vre", builtin.registers, {})
vim.keymap.set("n", "<leader>vm", builtin.marks, {})
vim.keymap.set("n", "<leader>vrc", function()
	require("jwyce.telescope").search_dotfiles()
end)
vim.keymap.set("n", "<leader>va", function()
	require("jwyce.telescope").anime_selector()
end)
